### ISSUE TITLE
Hotbar item name tooltips

### ISSUE THREAD

**Issue by gizmogoat** [telvarost/HudTweaks-StationAPI#1]
Tooltips above the hotbar that display what the item is when you scroll to it on your hotbar, similarly to newer Minecraft versions

**Comment by telvarost** [comment]
Good suggestion! Yep, I can add it :)
I've added it for you here in release v1.3.0
https://github.com/telvarost/HudTweaks-StationAPI/releases

**Comment by telvarost** [comment]
Oh its disabled by default, use modmenu with GlassConfigAPI to enable the setting (click the gear when selecting the mod in mod menu)
Hopefully that's okay. I usually keep my mods pretty close to vanilla b1.7.3 and then let people expand from there via configs 👍
