### ISSUE TITLE
(legacy console edition hud) I was told to open an issue about this

### ISSUE THREAD

**Issue by gamer-bruh** [telvarost/HudTweaks-StationAPI#2]
![Screenshot 2024-05-23 043855](https://github.com/telvarost/HudTweaks-StationAPI/assets/170628306/98675a99-5b0d-4b44-9843-5855dde8b91f)

**Comment by telvarost** [comment]
Added the pictured icons in v1.5.0
Feel free to provide assets if any other icons are desired
